name: equitrain
channels:
  - conda-forge
  - defaults
dependencies:
  # bzip2, libsqlite, libzlib, libffi, xz are included in conda
  # ca-certificates, openssl are included in conda
  - python=3.10
  - pip
  - setuptools
  - tk  # tkinter
  - pip:
      - -e .
