# M3GNet model configuration for Equitrain

# Data paths
train_file: data/train.h5
valid_file: data/valid.h5
output_dir: m3gnet_training

# Model configuration
model_wrapper: m3gnet
model: resources/models/m3gnet/m3gnet-initial-model.pt

# Training parameters
epochs: 100
batch_size: 32
lr: 0.001
verbose: 1
tqdm: true

# Loss weights
energy_weight: 1.0
forces_weight: 10.0
stress_weight: 0.1

# Loss function
loss_type: mse
loss_energy_per_atom: true

# Optimizer
optimizer: Adam
scheduler: ReduceLROnPlateau
scheduler_patience: 10
scheduler_factor: 0.5
scheduler_min_lr: 0.00001

# Distributed training
accelerator: auto
devices: auto
precision: 32
